#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    become_user: root
    get_url:
      url: https://valaxytech529.jfrog.io/artifactory/iwayqweb-libs-release-local/com/iwayq/iwayQApp/2.0-RELEASE/iwayQApp-2.0-RELEASE.war
      dest: .
      url_username: "rohan.reddy529@gmail.com"
      url_password: "4getmenot@J"

  - name: Rename .war Artifact
    command: mv iwayQApp-2.0-RELEASE.war iwayq.war
  
  - name: Build image and with build args
    become: true
    docker_image:
      name: iwayq
      build:
        path: .
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: rohan4linux@gmail.com
     password: Devops@1409

    
  - name: Push to docker hub
    docker_image:
      name: iwayq
      repository: docker.io/rohan4linux/iwayq:1.0
      push: yes
      source: local
