#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: iwayq-service
  namespace: prod
  labels:
    app: iwayq-app
spec:
  selector:
    app: iwayq-app

  type: {{ .Values.service.type }}
  ports:
  - nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
