# nameOverride: iwayq-web-app

# meta information. This data is used by operations to identify the deployed
# artifacts
meta:
  organization: "iwayq"
  team: "iwayq-web"
  product: "iwayqwebapp"

# Basic chart config, this represents configuration contract
# for the app
# key: value

deployment:
  # External configuration: declare secret/config map that
  # the chart should mount and use.

  # Mounts secret data to /deployments/config/secrets
  # secret: secret-name
  # Mounts configMap data to /deployments/config
  # configMap: configmap-name

  # activeMq:
  #   secret:
  #   url:
  cache:
    enabled: true

  replicaCount: 1
  image:
    # Define image, typically from docker repo, but can be 
    # image stream for local dev
    name: docker.io/iwayqdockertest/iwayq
    tag: 1.0
    pullPolicy: Always
    # Define image pull secrets if necessary
    # pullSecrets:
    #  -name: secretname
  jolokia:
    enabled: true
  # Override ports with collection of ports; by default 8080 is handled if
  # not specified.
  # ports:
  #  - name: 8080-tcp
  #    containerPort: 8080
  #    protocol: TCP
  liveness:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 3
    periodSeconds: 10
    path: /
    port: 8080
  readiness:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 3
    periodSeconds: 10
    path: /
    port: 8080
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}